# Each instruction in this file generates a new layer that gets pushed to your local image cache
FROM python:latest

# Identify the maintainer of an image
LABEL version="0.0.1"
LABEL maitainer="vikas"

# Add Python Script
ADD my_script.py /

# Execute python script
CMD [ "python", "./my_script.py" ]